### ISSUE TITLE
Sir, I need your help.

### ISSUE THREAD

**Issue by lovebdsobuj** [baivong/Celebrate-Pride-Canvas#1]
Sir, would you help me to use Celebrate-Pride with my country flag..?

**Comment by lelinhtinh** [comment]
I hope you'll like it: http://baivong.github.io/Bangladesh-Flag-Cover/

I've adjusted size parameters, and paint coatings national flag you as [hint on Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Bangladesh#/media/File:Bangladesh_National_Flag_construct.svg).
https://github.com/baivong/Celebrate-Pride-Canvas/blob/master/script.js#L103-L132
https://github.com/baivong/Bangladesh-Flag-Cover/blob/master/script.js#L103-L125

**Comment by lovebdsobuj** [comment]
Wow!
Great sir....

You made it, what I want.

Thanks lot sir.
